# URN: test:govern-providers:D001-UNIT-005-substrate-digest-covers-source-not-generated-caches
# Acceptance: acc:govern-providers:D001-UNIT-005-substrate-digest-covers-source-not-generated-caches
# WMBT: wmbt:govern-providers:D001
# Phase: GREEN
# Layer: unit
# Assertion: behavioral
"""GREEN Test for acc:govern-providers:D001-UNIT-005-substrate-digest-covers-source-not-generated-caches.

The substrate digest content-addresses SOURCE. Generated bytecode caches left
inside a vendored tree by a python run are not tamper — digesting them reported a
pristine tree as ``[TAMPERED]`` after a plain ``atdd enforce`` (#1603).

Excluding files from a tamper digest is how a guard goes blind, which would be
worse than the bug, so the negative half is the point of this test: a real source
edit, a real source deletion, and a non-bytecode file smuggled in under a
``__pycache__`` directory are each still caught.
"""
from __future__ import annotations

from pathlib import Path

from atdd.enforce.substrate_guard import verify_substrate

from .conftest import install_provider


def _verify(project_root: Path) -> bool:
    ok, verdicts = verify_substrate(project_root)
    assert verdicts, "no artifact was verified — the lock fixture is not wired"
    return ok


def test_substrate_digest_covers_source_not_generated_caches(tmp_path: Path) -> None:
    pkg = install_provider(tmp_path)  # digest recorded over the pristine source
    source = pkg / "cli" / "scan.py"
    original = source.read_bytes()

    assert _verify(tmp_path), "pristine vendored tree must verify intact"

    # A python run inside the tree: bytecode beside every imported module, and
    # pytest's cache dir at the rootdir. Neither is source; neither is tamper.
    (pkg / "cli" / "__pycache__").mkdir()
    (pkg / "cli" / "__pycache__" / "scan.cpython-313.pyc").write_bytes(b"\x00fake-bytecode")
    (pkg / "adapter").mkdir()
    (pkg / "adapter" / "run.pyo").write_bytes(b"\x00legacy-optimised-bytecode")
    (pkg / ".pytest_cache" / "v" / "cache").mkdir(parents=True)
    (pkg / ".pytest_cache" / "CACHEDIR.TAG").write_text("Signature: 8a477f59", encoding="utf-8")
    (pkg / ".pytest_cache" / "v" / "cache" / "lastfailed").write_text("{}", encoding="utf-8")

    assert _verify(tmp_path), "generated caches must not be read as tamper"

    # The exclusion is not a hiding place: __pycache__ is skipped by SUFFIX, not
    # by directory name, so a payload parked there is still digested.
    smuggled = pkg / "cli" / "__pycache__" / "payload.py"
    smuggled.write_text("import os  # payload\n", encoding="utf-8")
    assert not _verify(tmp_path), "a non-bytecode file under __pycache__ must still be tamper"
    smuggled.unlink()
    assert _verify(tmp_path)

    # POSITIVE CONTROL — a real source edit is still tamper, caches and all.
    source.write_bytes(original + b"\n# injected\n")
    assert not _verify(tmp_path), "an edited source file must still be tamper"
    source.write_bytes(original)
    assert _verify(tmp_path)

    # …and so is a real source deletion.
    source.unlink()
    assert not _verify(tmp_path), "a deleted source file must still be tamper"
